title: 2017 經濟播客競賽
headtitle: 經濟播客競賽
registrationurl: https://goo.gl/forms/vAD1OE9yiONnz5h32
uploadurl: https://docs.google.com/forms/d/e/1FAIpQLSdjp6kWOWSgZItYPYR_C101Jfl4V3Bxpcc6iZyiJ6xuZk5EIw/viewform?embedded=true
mainhosturl: http://www.ntpu.edu.tw/econ/
cohosturl: https://www.facebook.com/Emajortaiwanforu/
sponsorurl: https://www.facebook.com/groups/518140268277463/
google_analytics: UA-106134356-1

registrationdeadline: 2017/10/13
uploaddeadline: 2017/12/24
exhibitionperiod: 2017/12/27－12/29
outcomeannouncedate: 2018/1/3
awarddate: 另行公佈

author: 國立臺北大學。經濟學系
email: mtlin@gm.ntup.edu.tw
description: > # this means to ignore newlines until "baseurl:"
  2017 國立臺北大學第三屆經濟播客競賽

twitter_username: macrod68
github_username:  macrod68
facebook_pagename: ntpu.econ.podcast.champ.2017

sass:
    style: compressed
